#!/bin/bash
# 窗口模式修复验证脚本

echo "================================"
echo "🔧 窗口模式修复 - 验证脚本"
echo "================================"
echo ""

echo "📋 本次修复内容："
echo ""
echo "  ❌ 问题: 每次点击图标都创建新窗口"
echo "  ✅ 修复: 现在会聚焦已存在的窗口"
echo ""

echo "🔍 修复详情："
echo ""
echo "  1. 双层窗口查找策略"
echo "     - 优先使用记录的 windowId"
echo "     - 失败后遍历所有窗口"
echo ""
echo "  2. 精确 URL 匹配"
echo "     - 旧: url.includes()"
echo "     - 新: url.startsWith(chrome.runtime.getURL())"
echo ""
echo "  3. 完善状态管理"
echo "     - 创建时保存 ID"
echo "     - 关闭时清除 ID"
echo "     - 失败时重新查找"
echo ""

echo "================================"
echo "📝 测试步骤"
echo "================================"
echo ""

echo "1️⃣  重新加载扩展"
echo "   chrome://extensions/ → 点击「重新加载」"
echo ""

echo "2️⃣  打开 Service Worker 控制台"
echo "   点击扩展卡片上的「Service Worker」"
echo ""

echo "3️⃣  测试窗口聚焦（关键测试）"
echo ""
echo "   a) 首次点击扩展图标"
echo "      → 应该创建新窗口"
echo "      → 日志: '窗口创建成功，ID: xxx'"
echo ""
echo "   b) 最小化窗口或切换到其他窗口"
echo ""
echo "   c) 再次点击扩展图标"
echo "      → ✅ 应该聚焦已存在的窗口（不创建新窗口）"
echo "      → 日志: '✅ 成功聚焦已存在的窗口: xxx'"
echo ""
echo "   d) 重复 b-c 多次"
echo "      → ✅ 每次都应该聚焦同一个窗口"
echo "      → ❌ 不应该创建多个窗口"
echo ""

echo "4️⃣  测试窗口关闭后重新打开"
echo ""
echo "   a) 关闭窗口"
echo "      → 日志: '🔵 窗口关闭，ID: xxx'"
echo "              '✅ 清除记录的窗口ID'"
echo ""
echo "   b) 再次点击扩展图标"
echo "      → 应该创建新窗口"
echo "      → 日志: '窗口创建成功，ID: yyy'"
echo ""

echo "================================"
echo "✅ 预期结果"
echo "================================"
echo ""
echo "  正确行为: 只保持一个窗口，点击图标只聚焦"
echo "  错误行为: 每次点击都创建新窗口"
echo ""

echo "================================"
echo "📊 成功日志示例"
echo "================================"
echo ""
echo "首次点击:"
echo "  🔵 当前记录的 currentWindowId: null"
echo "  窗口创建成功，ID: 123"
echo ""
echo "第二次点击:"
echo "  🔵 当前记录的 currentWindowId: 123"
echo "  ✅ 成功聚焦已存在的窗口: 123"
echo ""
echo "第三次点击:"
echo "  🔵 当前记录的 currentWindowId: 123"
echo "  ✅ 成功聚焦已存在的窗口: 123"
echo ""

echo "详细测试场景请查看: WINDOW_MODE_TEST.md"
echo ""
echo "================================"

# 询问是否打开扩展管理页面
read -p "是否现在打开 Chrome 扩展管理页面进行测试? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    open "chrome://extensions/"
    echo ""
    echo "✅ 已打开扩展管理页面"
    echo "📌 记得点击「重新加载」按钮！"
    echo "📌 记得打开「Service Worker」控制台查看日志！"
fi

